# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCInterview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCInterview
  pod "Masonry"

  target 'OCInterviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCInterviewUITests' do
    # Pods for testing
  end

end
